import type { TodoItem } from './types'

const now = Date.now()
const DAY = 86_400_000

export const MOCK_FLOWS: TodoItem[] = [
  {
    id: 'flow-1',
    goal: 'Logo Rebrand',
    domain: 'brand',
    toneProfile: 'calm_mentor',
    status: 'active',
    createdAt: now - DAY * 3,
    updatedAt: now - 3_600_000,
    steps: [
      {
        id: 'f1-s1',
        text: 'Gather brand references and mood board',
        domainTag: 'research',
        estimatedMinutes: 30,
        status: 'completed',
        completedAt: now - DAY * 2,
      },
      {
        id: 'f1-s2',
        text: 'Sketch three logo directions',
        domainTag: 'design',
        estimatedMinutes: 60,
        status: 'completed',
        completedAt: now - DAY,
      },
      {
        id: 'f1-s3',
        text: 'Drafting vector variations',
        domainTag: 'design',
        estimatedMinutes: 90,
        status: 'pending',
      },
      {
        id: 'f1-s4',
        text: 'Client review round',
        domainTag: 'review',
        estimatedMinutes: 30,
        status: 'pending',
      },
      {
        id: 'f1-s5',
        text: 'Finalise and export assets',
        domainTag: 'delivery',
        estimatedMinutes: 30,
        status: 'pending',
      },
    ],
  },
  {
    id: 'flow-2',
    goal: 'Short Story Collection',
    domain: 'writing',
    toneProfile: 'gentle_guide',
    status: 'active',
    createdAt: now - DAY,
    updatedAt: now - 1_800_000,
    steps: [
      {
        id: 'f2-s1',
        text: 'Chapter 1 world-building',
        domainTag: 'writing',
        estimatedMinutes: 120,
        status: 'pending',
      },
      {
        id: 'f2-s2',
        text: 'Character profiles for main cast',
        domainTag: 'writing',
        estimatedMinutes: 60,
        status: 'pending',
      },
      {
        id: 'f2-s3',
        text: 'Draft chapter 1',
        domainTag: 'writing',
        estimatedMinutes: 180,
        status: 'pending',
      },
      {
        id: 'f2-s4',
        text: 'Self-edit and revise',
        domainTag: 'writing',
        estimatedMinutes: 60,
        status: 'pending',
      },
      {
        id: 'f2-s5',
        text: 'Share with beta reader',
        domainTag: 'review',
        estimatedMinutes: 0,
        status: 'pending',
      },
    ],
  },
  {
    id: 'flow-3',
    goal: 'Morning Running Habit',
    domain: 'fitness',
    toneProfile: 'hype_coach',
    status: 'completed',
    createdAt: now - DAY * 14,
    updatedAt: now - DAY * 2,
    completedAt: now - DAY * 2,
    steps: [
      {
        id: 'f3-s1',
        text: 'Set alarm 30 min earlier',
        domainTag: 'planning',
        estimatedMinutes: 5,
        status: 'completed',
        completedAt: now - DAY * 12,
      },
      {
        id: 'f3-s2',
        text: 'Lay out running kit the night before',
        domainTag: 'habit',
        estimatedMinutes: 5,
        status: 'completed',
        completedAt: now - DAY * 10,
      },
      {
        id: 'f3-s3',
        text: 'Complete first 5-minute run',
        domainTag: 'exercise',
        estimatedMinutes: 15,
        status: 'completed',
        completedAt: now - DAY * 8,
      },
      {
        id: 'f3-s4',
        text: 'Build to 20 minutes over two weeks',
        domainTag: 'exercise',
        estimatedMinutes: 20,
        status: 'completed',
        completedAt: now - DAY * 2,
      },
    ],
  },
]
